### ISSUE TITLE
此处一会是bool一会是int，应该使用json.RawMessage或者interface{}

### ISSUE THREAD

**Issue by orestonce** [TuyaInc/tuya_cloud_sdk_go#1]
https://github.com/TuyaInc/tuya_cloud_sdk_go/blob/f5c575ab1e7bcf20cd59376a614f81c24fc1d325/api/device/get_device.go#L41

**Comment by LvBay** [comment]
@orestonce  上层接口这个字段类型暂时无法统一，稍后会改成interface

**Comment by orestonce** [comment]
👌

**Comment by LvBay** [comment]
已合并，多谢反馈！
